name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - stable

env:
  SOLUTION_PATH: XSM.sln
  PROJECT_PATH: ./XiaomiSoftwareManager/XiaomiSoftwareManager.csproj
  PROJECT_NAME: XiaomiSoftwareManager

jobs:
  run-tests:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore NuGet Packages
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    - name: Run Tests
      run: |
        dotnet test ${{ env.SOLUTION_PATH }} --logger "console;verbosity=detailed" --verbosity normal
    
